---
title: "Research: Working Papers"
href: cyberattacks.jpg
---

1.  Cybersecurity in Pakistan: Impact of The Prevention of Electronic Crimes Act

Abstract

The purpose of this paper is to understand the current state of cybersecurity in Pakistan. Specifically, the characterists of cyberattacks in Pakistan and the impact of Pakistan's first major cybersecuity policy titled the "Prevention of Electronic Crimes Act" (or PECA) which was passed in 2016. The field of cybersecurity research suffers from a lack of publicly available data for researchers to use. At present, there is no dataset on cyberattacks in Pakistan. This study will fill this gap by introducing a novel dataset on cyberattacks reported in Pakistan from 2008 to 2021. The second dataset is regarding website defacements in Pakistan published by a private cybersecurity firm.

Conferences: 

American Political Science Association (2023)

Midwest Political Science Association (2024)

2.  Dataset: Cyberattacks in Pakistan

Version 1 is available at Harvard data verse:

https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/V3ZTGO

This research creates the first dataset on cyberattacks reported in Pakistan. This novel dataset uses secondhand data collected from newspaper articles, journals, and government reports. The timeline is 2008--2022. The dataset has a sample size of 38. Every effort was made to collect all the reports on cyberattacks in Pakistan, but this research does not claim that every cyberattack reported in Pakistan is included in this dataset. Most cyberattacks reported have two sources, but a few cyberattacks reported only had one source. The dataset includes information on the target, month, year, type of attack, affiliation, target category, system vulnerability, software used, data sold, financial loss reported, the sources of the cyberattack reported, and the title of the newspaper article or report. The codebook explains all the columns in detail.

3.  Did the Budapest Convention Deter Cybercrime? An Event Study Using a Panel of Countries

Authors: Humza Khan, Andrew Fowler, and Dr. Pengfei Zhang.

Abstract

This research uses a difference-in-differences model to study the impact of the Budapest Convention on cyberattacks received by a country from 2001 to 2021. This paper investigates whether country-level enforcement of the Budapest Convention deters cyber-attacks received. Our event study design uses staggered timing i.e., countries adopted and implemented the treaty at different timings. This study compares the rate of attacks on signatory countries prior to a country's adoption of the Convention and after the Convention entered into force.
